### PR TITLE
Use bitwise instead of boolean OR

### PR DESCRIPTION
**Pull request by nbougalis**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Suggested commit message:
```
Check ostream modifier correctly
```
Also CHANGELOG.md needs an updating

**Comment by ximinez** [comment]
s/OR/AND/

**Comment by nbougalis** [comment]
D'oh. `AND`, yes.

**Comment by vinniefalco** [comment]
Just a reminder, we need to analyze the calls to `log.flush()` to determine if they are still necessary (since I added them to work around this `unitbuf` bug):
```
extras\beast\unit_test\reporter.hpp(286): os_.flush();
extras\beast\unit_test\suite.hpp(356): suite_.log.flush();
extras\beast\unit_test\suite.hpp(397): suite_.log.flush();
```

**Comment by nbougalis** [comment]
With this change, the calls to `flush` are no longer needed.

**Comment by vinniefalco** [comment]
Please remove the calls to `flush` then!

**Comment by vinniefalco** [comment]
Fixed in **1.0.0-b29**

**Pull request closed without merging**
