### PR TITLE
Version 73

### PR DESCRIPTION
**Pull request by vinniefalco**
* Jamroot tweak
* Verify certificates in SSL clients
* Adjust benchmarks
* Initialize local variable in basic_parser

HTTP:

* basic_parser optimizations
* Add basic_parser tests

API Changes:

* Refactor header and message constructors
* serializer::next replaces serializer::get

Actions Required:

* Evaluate each message constructor call site and
  adjust the constructor argument list as needed.

* Use serializer::next instead of serializer::get at call sites

Documentation preview:
http://vinniefalco.github.io/stage/beast/v73/

### CODE REVIEW

**Comment by vinniefalco** [comment]
@octopus-prime Could you please look this over and let me know if you think it should be merged as-is?

**Comment by octopus-prime** [comment]
BTW: could build on osx using bjam without problems.

**Comment by vinniefalco** [comment]
Thanks, glad to hear it!!

**Comment by vinniefalco** [comment]
Merged

**Pull request closed without merging**
