### PR TITLE
Version 70

### PR DESCRIPTION
**Pull request by vinniefalco**
* Serialize in one step when possible
* Add basic_parser header and body limits
* Add parser::on_header to set a callback

API Changes:

* Rename to message::base
* basic_parser default limits are now 1MB/8MB

Actions Required:

* Change calls to message::header_part() with message::base()

* Call body_limit and/or header_limit as needed to adjust the
  limits to suitable values if the defaults are insufficient.

Documentation preview:
http://vinniefalco.github.io/stage/beast/v70

### CODE REVIEW

**Comment by vinniefalco** [comment]
Apparently I can't get pull requests right this week (`_attribute__` anyone?) So if you would like to sign off on this @octopus-prime I would appreciate it. I've invited you to become a Collaborator on the repository.

**Comment by octopus-prime** [comment]
> I've invited you to become a Collaborator on the repository.

How do i accept this?

**Comment by vinniefalco** [comment]
>How do i accept this?

I think its either a GitHub notification or email

**Comment by octopus-prime** [comment]
Found it. Accepted it. Thanks!

**Comment by octopus-prime** [comment]
> So if you would like to sign off on this @octopus-prime I would appreciate it.

What do you mean? What do i have to do?

**Comment by vinniefalco** [comment]
>What do you mean? What do i have to do?

I added you as a reviewer so there's a "Start Review" button and if you think this branch is okay then just press "Accept" or whatever its called, if you look around on the page you'll find it.

**Comment by octopus-prime** [comment]
I am unsure... 

bildschirmfoto vom 2017-06-28 23-02-29
bildschirmfoto vom 2017-06-28 23-02-54

Simply "Rebase and merge" or "Review"+"Approve"?

**Comment by vinniefalco** [comment]
You can just do the reviews, I'll take care of merging the branches. Never use the GitHub interface to merge the branch (well don't merge at all, I will do it) - sometimes Github creates a merge commit and I try very hard to keep the history linear. Sometimes merge commits are unavoidable but when they happen they are strategically planned.

**Pull request merged**
