### PR TITLE
Add options for tests and examples

### PR DESCRIPTION
**Pull request by xsacha**
#442

### CODE REVIEW

**Comment by xsacha** [comment]
Added #443

**Comment by vinniefalco** [comment]
I don't understand CMake well enough to evaluate these changes but an "install" is sort of out of scope, as this is being proposed as a Boost library and therefore, does not require an "install" target since it will adhere to the Boost directory structure.

**Comment by xsacha** [comment]
If it were to be included in Boost, then it would not need a CMakeLists.txt, correct? Boost unfortunately doesn't use CMake. So I am not sure how it is related.

**Comment by xsacha** [comment]
I have switched back to a single commit.

**Comment by vinniefalco** [comment]
>If it were to be included in Boost, then it would not need a CMakeLists.txt

Its not required, but I need CMakeLists.txt so I can generate Visual Studio project files (.vcxproj). That's my primary development environment.

**Comment by xsacha** [comment]
OK. So what's the problem? It will still make these .vcxproj :)

**Comment by vinniefalco** [comment]
Let me make sure I understand this (I am no CMake expert) - this change only adds the option of not building the examples or tests?

**Comment by xsacha** [comment]
Yes and they are enabled by default.

**Comment by vinniefalco** [comment]
While these changes look like they do what is intended, this is why I think we should not merge them:

* They have little meaning when Beast becomes part of Boost

* The build options and install target are not part of my workflow, and not part of the continuous integration scripts, so they will not receive testing. I won't know if I break them. Which means, they will break.

**Comment by xsacha** [comment]
I think this whole file will have little meaning when Beast becomes part of Boost unless it is still used for Travis CI (but I think Boost uses some other CI).

These options should not be hard to maintain but I will fix them up if needed. It should be as simple as adding new tests inside the if (Beast_BUILD_TESTS) and new examples inside the if (Beast_BUILD_EXAMPLES).

**Comment by vinniefalco** [comment]
The formal review is July 1st, just 19 days!

**Comment by xsacha** [comment]
Oh I see! But the project isn't even API complete yet?

**Comment by vinniefalco** [comment]
>But the project isn't even API complete yet?

It is **very** close to being complete.

**Comment by xsacha** [comment]
@ksergey has a newer version of this rebased on v61 so this can be closed.

**Pull request closed without merging**
