### PR TITLE
Fix Deferred Body Type Example inconsistencies

### PR DESCRIPTION
**Pull request by eliottparis**
Fix issue #675

### CODE REVIEW

**Comment by vinniefalco** [comment]
This will go into the **boost** branch

**Comment by eliottparis** [comment]
Ok sorry, should I close this PR and open another one into the **boost** branch ?

**Comment by vinniefalco** [comment]
>Ok sorry, should I close this PR and open another one into the boost branch ?

Thanks but that's not necessary, I've already cherry-picked your changes into it:
https://github.com/vinniefalco/beast/commits/boost

**Comment by vinniefalco** [comment]
The issue will automatically close itself since you put the issue number in it (thanks for that!). I'll keep it open as a reminder that there's a contributed work in the feature branch to make sure it doesn't get forgotten on any rebase. And also, visible contributions look nice and encourage more participation :)

**Comment by vinniefalco** [comment]
Your changes are listed here: https://github.com/boostorg/beast/pull/677

**Pull request closed without merging**
