### PR TITLE
Using SSE4.2 intrinsics in basic_parser if available

### PR DESCRIPTION
**Pull request by octopus-prime**
issue #585

### CODE REVIEW

**Comment by glenfe** [comment]
Why is this assuming that __get_cpuid exists just as long as the compiler is not MSVC (or some compiler pretending to be MSVC)?

**Comment by glenfe** [comment]
Why is this assuming that __get_cpuid exists just as long as the compiler is not MSVC (or some compiler pretending to be MSVC)?

**Comment by vinniefalco** [comment]
This has to be rebased against the **v74** which I am about to put up - GitHub is behaving weirdly because these two branches are similar.

**Comment by vinniefalco** [comment]
Please continue the discussion here https://github.com/vinniefalco/Beast/pull/613

**Comment by octopus-prime** [comment]
@glenfe Since currently supported compilers are msvc, gcc and clang. IMO gcc and clang are happy with `__get_cpuid`

**Comment by vinniefalco** [comment]
@glenfe What's a better way?

**Comment by octopus-prime** [comment]
> This has to be rebased against the v74 which I am about to put up - GitHub is behaving weirdly because these two branches are similar.

any action needed by me?

**Comment by vinniefalco** [comment]
>any action needed by me?

Yes, just rebase it interactively (`git fetch upstream` then `git rebase -i upstream/v74` where `upstream` is the remote `git@github.com:vinniefalco/Beast.git`), delete the commits that aren't yours, and accept

**Comment by glenfe** [comment]
Supporting only three compilers is perfectly fine, but let's not assume that if not compiler X detected, that it must be one of Y or Z. i.e. The way the original code was detecting C++ implementations (i.e. an error directive with a meaningful message if not one of the supported compilers) was better.

For something like this, it isn't a big deal, because ultimately it will just result in a compile time error anyway, but in general as a good practice for Boost libraries: If you're targeting implementation specifics, do it only after you've explicitly detected the implementation.

**Comment by glenfe** [comment]
Also, prefer use BOOST_MSVC from Boost.Config to determine if the compiler is truly MSVC, because compilers that choose to pretend to be MSVC may define _MSC_VER, and may not have the same behavior (or the same intrinsics).

**Comment by octopus-prime** [comment]
@glenfe 

Can you give a working example for this pseudocode using the right BOOST_xxx macros?

```
if windows
...
else if gcc or clang
...
else
...
end
```

**Comment by vinniefalco** [comment]
I am confused on how to do this as well.

**Comment by glenfe** [comment]
For just that pseudo code:
```
#if defined(BOOST_MSVC) && BOOST_MSVC >= x
// ...
#elif (defined(BOOST_GCC) && BOOST_GCC > y) || (defined(BOOST_CLANG) && BOOST_CLANG > z)
// ...
#else
// ...
#endif
```
Of course, within each implementation detection block, you will want to check additional implementation specific things.

**Comment by octopus-prime** [comment]
@glenfe Thanks!
@vinniefalco If we want to use these `x, y and z` versions - what are the minimal requirements for the compiler versions? I only found `When using Microsoft Visual C++, Visual Studio 2015 Update 3 or later is required.` So what versions are required for gcc and clang?

BTW:
Does anybody know whether we can use the clang version on OSX too?
The Apple-LLVM compiler says something about version 7.x and 8.x.
And http://llvm.org/ says something about a LLVM 5.0 will come **in future**.
So clang versions on OSX are useless??

**Comment by vinniefalco** [comment]
Beast needs good C++11 support, so Visual Studio 2015 Update 3 is a reasonable minimum.

Right now the farthest back Beast goes on gcc is 4.8. That's probably a reasonable lower limit, any lower and you start running into compiler bugs that are very hard to fix in Beast.

For clang, I don't know.

**Comment by octopus-prime** [comment]
Ignoring the compiler versions for the moment.
When we change the definition of `BEAST_NO_INTRINSICS` to

```
#ifndef BEAST_NO_INTRINSICS
# if defined(BOOST_MSVC) || ((defined(BOOST_GCC) || defined(BOOST_CLANG)) && defined(__SSE4_2__))
#  define BEAST_NO_INTRINSICS 0
# else
#  define BEAST_NO_INTRINSICS 1
# endif
#endif
```

and all other cpuid and SSE4.2 stuff will guarded by `!BEAST_NO_INTRINSICS` so we are safe with

```
#if defined(BOOST_MSVC)
#include <intrin.h> // __cpuid
#else
#include <cpuid.h>  // __get_cpuid
#endif
```

?!

@glenfe @vinniefalco What do you think?

**Comment by vinniefalco** [comment]
I don't know how any of those BOOST macros work, and I am unfamiliar with the other toolchains' macros. So I cannot evaluate this change.

**Pull request closed without merging**
