### PR TITLE
Travis CI updates:

### PR DESCRIPTION
**Pull request by sublimator**
* Use clang 3.8
* Add msan/usan variants
* Make sure (correct) llvm-symbolizer is on PATH
* Run autobahn/valgrind tests when target branch in {master, develop}
* Add coveralls

### CODE REVIEW

**Comment by vinniefalco** [comment]
Does the *`ws`* branch need this commit? Or a variant of it?

**Comment by sublimator** [comment]
Yes, cherry-pick this commit for #14, replacing the existing one there

**Comment by vinniefalco** [comment]
Please squash and rebase, there are merge conflicts.

**Comment by sublimator** [comment]
Ok, will rebase on top of the ws branch

**Comment by vinniefalco** [comment]
??

**Comment by sublimator** [comment]
What's the ?? regarding?

**Comment by vinniefalco** [comment]
Why is this closed?

**Comment by sublimator** [comment]
It was targeting master. I opened another WIP branch based on ws with a
commit to cherry pick onto ur ws branch in place of the current one.

**Pull request closed without merging**
