### PR TITLE
Mingw build

### PR DESCRIPTION
**Pull request by e-fominov**
I was unable to build Beast as-is with MinGW and MSCV. This PR makes it possible
Tested with MINGW 6.2 x64, and MSVC 2015 x64, Windows 7

### CODE REVIEW

**Comment by vinniefalco** [comment]
Thanks! This looks very promising, although realistically I have no way to test it since I don't use MinGW. Is there some way to have MinGW as a target on Travis?

**Comment by e-fominov** [comment]
I dont have much experience with Travis. MinGW itself is GCC-based and there will be no syntax differences, except the libc is missing on MinGW.

MinGW has cross-compiler that can be installed into Linux platform and also I found one stackoverflow post where it seems possible to use MinGW with Travis: http://stackoverflow.com/questions/28155308/how-to-cross-compile-with-mingw-on-linux-for-windows

**Comment by vinniefalco** [comment]
Hmm...unfortunately these changes break 64-bit MSVC builds and I'm not sure why. This is the command line I used to build the solution and project files after cherry-picking your commits:
```
cd bin64
cmake -G"Visual Studio 14 2015 Win64" ..
```

**Comment by vinniefalco** [comment]
I think I see what's happening. These are the lines causing problems:
```
find_package(Boost REQUIRED COMPONENTS coroutine context thread filesystem program_options system)
link_directories(${Boost_LIBRARY_DIRS})
link_libraries(${Boost_LIBRARIES})
```

Unfortunately with MSVC, we can't use the package finder to set the library directories, because there is no way to distinguish between 32 versus 64 bit builds. What I do is add a path to the Boost 32 bit libraries in the Microsoft.Cpp.Win32.user property sheet, and add a different path to the Boost 64 bit libraries in the Microsoft.Cpp.x64.user property sheet. If we were to use find_package and link_directories for this, then targeting both 32 and 64 bit builds in separate solutions would no longer be possible.

These are the steps I use to generate the separate solutions, please try them and see if they work with your changes:
```
cd bin
cmake ..
cd ../bin64
cmake -G"Visual Studio 14 2015 Win64" ..
```

**Comment by e-fominov** [comment]
Do you have boost compiled for x64?   I have tested this PR with MSVCx64 - compiles well. But my boost is compiled for x64
Looks like D:\lib\boost_1_61_0\stage\lib\ libraries on your machine are x86

This problem is because your original CMakeLists.txt file had no find_module(Boost) for Win32 compilation. Looks like you have something in your System Environment variables that makes it find boost in incorrect place. Normally CMake's findboost module searches it in c:\boost

Now it tries to find boost and finds it in D:\lib\boost_1_61_0\stage\lib\, which contain x86 libraries
To make it use Boost from other folder, its possible to pass additional params to cmake:

```
cd bin64
cmake -G"Visual Studio 14 2015 Win64" .. -DBOOST_INCLUDEDIR=d:\boost64\include -DBOOST_LIBRARYDIR=d:\boost64\lib
```

**Comment by vinniefalco** [comment]
I have 32-bit boost libraries in `D:\lib\boost_1_61_0\stage` and 64-bit boost libraries in `d:\lib\boost_1_61_0\stage64`. I also have `$BOOST_ROOT` set to `/d/lib/boost_1_61_0/`.

You're telling me that I should manually specify the header include and library include paths every time I want to rebuild the visual studio project files?

**Comment by vinniefalco** [comment]
I tried this line with your changes:
```
cmake -G"Visual Studio 14 2015 Win64" .. -DBOOST_INCLUDEDIR=D:\lib\bo
ost_1_61_0 -DBOOST_LIBRARYDIR=d:\lib\boost_1_61_0\stage64
```

But the Additional Library Directories under Linker properties shows
```
D:/lib/boost_1_61_0/stage/lib;D:/lib/boost_1_61_0/stage/lib/$(Configuration);%(AdditionalLibraryDirectories)
```

**Comment by e-fominov** [comment]
Try adding -DBoost_NO_SYSTEM_PATHS=ON

What is the version of CMake you are using? If your version < 3.6.2, it may not know about boost version 1.61. You can tell him that this version exists:

-DBoost_ADDITIONAL_VERSIONS=1.61

**Comment by e-fominov** [comment]
I have just checked out master branch CMakeFiles.txt, and MSVC told me that he cant compile:

```
C:\work\Beast\include\beast/core/detail/ci_char_traits.hpp(11): fatal error C1083: Unable to open include file: boost/range/algorithm/equal.hpp: No such file or directory (compiling C:\work\Beast\test\http\parser_bench.cpp) [C:\work\Beast\b15\test\http\bench-tests.vcxproj]
...
```

Are you sure, it was compiling with previous version of CMakeFiles.txt?

**Comment by vinniefalco** [comment]
I'm on CMake 3.6.0. I will try updating it.

Yes, I am sure that the tip of *master* compiles with CMake. I do all of my development in Visual Studio and I use CMake to generate the project files. You need to add the include path and library path to your Microsoft.Cpp.x64.user property sheet (View -> Property Manager).

**Comment by vinniefalco** [comment]
Updating to CMake 3.6.2 had no effect on the result, I get the same errors. This is the command line I used:
```
cd bin64
rm -rf *
cmake -G"Visual Studio 14 2015 Win64" .. -DBOOST_INCLUDEDIR=D:\lib\boost_1_61_0 -DBOOST_LIBRARYDIR=d:\lib\boost_1_61_0\stage64
```
This is what the linker properties on the resulting project look like:
image

**Comment by e-fominov** [comment]
I have restored original code for MSVC compilation process. MinGW compiles well on my pc
To compile MSVC I need to open .vcproj in Studio and set directories manually

**Comment by vinniefalco** [comment]
This works for me now:
https://github.com/vinniefalco/Beast/commits/mingw

It will go into b14, so I'll close this. Thanks for your contribution!

**Pull request closed without merging**
