### PR TITLE
cmake: add missing -pthread to core-tests and websocket-tests

### PR DESCRIPTION
**Pull request by cbodley**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Reviewers: @seelabs

**Comment by seelabs** [comment]
:+1: Using the imported target seems to be the preferred over ${CMAKE_THREAD_LIBS_INIT}. On my system (ubuntu 16.04) they seem to do the same thing, though looking at https://github.com/Kitware/CMake/blob/master/Modules/FindThreads.cmake there are differences on other systems.

Good change.

**Comment by vinniefalco** [comment]
@seelabs Is there an easy way to address #28 in this PR?

**Comment by vinniefalco** [comment]
This is a clear improvement and it passes review.
:+1:

**Comment by vinniefalco** [comment]
@cbodley Thanks!

**Comment by vinniefalco** [comment]
This is now part of #29

**Pull request closed without merging**
